[package]
name = "tasklog"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.37", features = ["derive"] }
crossterm = "0.29.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
